//
//  CurrencyConverterRouter.swift
//  CurrencyConversion
//
//  Created by Henrikas J on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrencyConverterRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CurrencyConverterDataPassing
{
//  var dataStore: CurrencyConverterDataStore? { get }
}

class CurrencyConverterRouter: NSObject, CurrencyConverterRoutingLogic, CurrencyConverterDataPassing
{
//  weak var viewController: CurrencyConverterViewController?
//  var dataStore: CurrencyConverterDataStore?
}
