//
//  CurrencyConverterPresenter.swift
//  CurrencyConversion
//
//  Created by Henrikas J on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyConverterPresentationLogic
{
  func presentSomething(response: CurrencyConverter.Something.Response)
}

class CurrencyConverterPresenter: CurrencyConverterPresentationLogic
{
  weak var viewController: CurrencyConverterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CurrencyConverter.Something.Response)
  {
    let viewModel = CurrencyConverter.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
