//
//  CurrencyConverterModels.swift
//  CurrencyConversion
//
//  Created by Henrikas J on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CurrencyConverter
{
  // MARK: Use cases
  
  enum FetchCurrencyConversion
  {
    struct Request
    {
      var fromAmount: Double
      var fromCurrency: String
      var toCurrency: String
    }

    struct Response
    {
    }

    struct ViewModel
    {
    }
  }

  enum Something
  {
    struct Request
    {
    }

    struct Response
    {
    }

    struct ViewModel
    {
    }
  }
}
