//
//  CurrencyConverterViewController.swift
//  CurrencyConversion
//
//  Created by Henrikas J on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Stevia

protocol CurrencyConverterDisplayLogic: class
{
  func displaySomething(viewModel: CurrencyConverter.Something.ViewModel)
}

class CurrencyConverterViewController: UIViewController, CurrencyConverterDisplayLogic
{
    
  var interactor: CurrencyConverterBusinessLogic?
  var router: (NSObjectProtocol & CurrencyConverterRoutingLogic & CurrencyConverterDataPassing)?

  private let v = CurrencyConverterView()
  override func loadView() { view = v }

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CurrencyConverterInteractor()
    let presenter = CurrencyConverterPresenter()
    let router = CurrencyConverterRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()

    // TODO: Remove on release build!
    on("INJECTION_BUNDLE_NOTIFICATION") {
        self.view = CurrencyConverterView()
    }
//
//    let viewBox: UIView = {
//        let view = UIView()
//        view.translatesAutoresizingMaskIntoConstraints = false
//        view.heightAnchor.constraint(equalToConstant: 50).isActive = true
//        view.widthAnchor.constraint(equalTo: view.heightAnchor).isActive = true
//        view.backgroundColor = .black
//
//        return view
//    }()
//
//    view.addSubview(viewBox)
//    viewBox.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
//    view.backgroundColor = .blue

    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = CurrencyConverter.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: CurrencyConverter.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
