//
//  CurrencyConverterModels.swift
//  CurrencyConversion
//
//  Created by Henrikas J on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import RealmSwift

protocol DisplayedObject {

}

enum ErrorType: LocalizedError {
  case InvalidConversionInput(message: String? = nil)
  case DatabaseRequestedObjectNotExisting(message: String? = nil)
  case UnsuportedCurrencyRequest(message: String? = nil)
  case InsufficientConvertingFunds(message: String)
}

extension ErrorType {
  var errorDescription: String? {
    switch self {
    case let .InsufficientConvertingFunds(message):
      return message
    case let .InvalidConversionInput(message):
      return message
    case let .DatabaseRequestedObjectNotExisting(message):
      return message
    case let .UnsuportedCurrencyRequest(message):
      return message
    }
  }
}

enum CurrencyConverter {
  // MARK: Use cases
  
  enum FetchCurrencyConversion {
    struct Request {
      var fromAmount: String
      var fromCurrency: String
      var toCurrency: String
      var toCell: CollectionView.CellType?
    }

    struct Response {
      var fromConversion: ConvertedCurrency?
      var toConversion: ConvertedCurrency?
      var toCell: CollectionView.CellType?
      var error: Error?
    }

    struct ViewModel {
      var receive: String
    }
  }

  enum FetchCurrencyConversionContract {
    struct Request {
      var fromAmount: String
      var fromCurrency: String
      var toCurrency: String
    }

    struct Response {
      var fromAmount: String?
      var totalAmount: Double?
      var fromCurrency: String?
      var toCurrency: String?
      var toAmount: String?
      var feeRate: Double?
      var fee: Double?
      var error: Error?
    }

    struct ViewModel {
      var message: String
    }
  }

  enum CompleteCurrencyConversionContract {
    struct Request {
      var fromAmount: String
      var fromCurrency: String
      var toCurrency: String
    }

    struct Response {
      var totalAmount: Double?
      var fromCurrency: String?
      var toCurrency: String?
      var toAmount: String?
      var fee: Double?
      var error: Error?
    }

    struct ViewModel {
      var message: String
    }
  }

  enum ErrorAlert {
    struct Request {
    }

    struct Response {
      var error: Error
    }

    struct ViewModel {
      var title: String
      var message: String
      var buttonTitle: String
      var error: Error?
    }
  }

  enum CollectionView {
    enum CellType {
      case Balance
      case CurrencyExchange
    }

    struct Request {
      var type: CellType
    }

    struct Response {
      struct BalanceCell {
        var objects: Results<StoredCurrency>?
        var error: Error?
      }
      struct CurrencyExchangeCell {
        var image: UIImage?
        var title: String?
        var value: String?
        var error: Error?
      }
    }

    struct ViewModel {
      struct BalanceCell: DisplayedObject {
        var currencyName: String
        var holdingAmount: String
      }

      struct CurrencyExchangeCell: DisplayedObject {
        var image: UIImage?
        var title: String
        var value: String
        var selectedCurrency: String?
      }

      var displayedObjects: [DisplayedObject]
    }
  }

  enum FetchAvailableCurrencies {
    struct Request {
    }

    struct Response {
      var currencies: [String]
    }

    struct ViewModel {
      var currencies: [String]
    }
  }
}
