//
//  CurrencyConverterInteractor.swift
//  CurrencyConversion
//
//  Created by Henrikas J on 09/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyConverterBusinessLogic
{
  func doSomething(request: CurrencyConverter.Something.Request)
}

protocol CurrencyConverterDataStore
{
  //var name: String { get set }
}

class CurrencyConverterInteractor: CurrencyConverterBusinessLogic, CurrencyConverterDataStore
{
  var presenter: CurrencyConverterPresentationLogic?
  var worker: CurrencyConverterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CurrencyConverter.Something.Request)
  {
    worker = CurrencyConverterWorker()
    worker?.doSomeWork()
    
    let response = CurrencyConverter.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
